DAX_Block2_2024/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAX_Block2_2024.Entities;
using DAX_Block2_2024.Models;

namespace DAX_Block2_2024.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly Web_Chia_Se_Tai_LieuContext _context;

        public DocumentsController(Web_Chia_Se_Tai_LieuContext context)
        {
            _context = context;
        }

        // GET: Documents
        [Authentication]

        public async Task<IActionResult> Index()
        {
            var web_Chia_Se_Tai_LieuContext = _context.Documents.Include(d => d.PostByNavigation);
            return View(await web_Chia_Se_Tai_LieuContext.ToListAsync());
        }

        // GET: Documents/Details/5
        [Authentication]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.PostByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Documents/Create
        [Authentication]

        public IActionResult Create()
        {
            ViewData["PostBy"] = new SelectList(_context.Users, "Id", "Address");
            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> Create([Bind("Id,Name,Description,Content,DatePost,PostBy,Image,FilePath,Rate,Status,Price,TagsId,CategoriesId")] Document document)
        {
            if (ModelState.IsValid)
            {
                _context.Add(document);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostBy"] = new SelectList(_context.Users, "Id", "Address", document.PostBy);
            return View(document);
        }

        // GET: Documents/Edit/5
        [Authentication]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents.FindAsync(id);
            if (document == null)
            {
                return NotFound();
            }
            ViewData["PostBy"] = new SelectList(_context.Users, "Id", "Address", document.PostBy);
            return View(document);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Content,DatePost,PostBy,Image,FilePath,Rate,Status,Price,TagsId,CategoriesId")] Document document)
        {
            if (id != document.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(document);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentExists(document.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PostBy"] = new SelectList(_context.Users, "Id", "Address", document.PostBy);
            return View(document);
        }

        // GET: Documents/Delete/5
        [Authentication]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Documents
                .Include(d => d.PostByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var document = await _context.Documents.FindAsync(id);
            _context.Documents.Remove(document);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authentication]

        private bool DocumentExists(int id)
        {
            return _context.Documents.Any(e => e.Id == id);
        }
    }
}

DAX_Block2_2024/Controllers/ListNewsUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAX_Block2_2024.Entities;
using DAX_Block2_2024.Models;

namespace DAX_Block2_2024.Controllers
{
    public class ListNewsUserController : Controller
    {
        private readonly Web_Chia_Se_Tai_LieuContext _context;

        public ListNewsUserController(Web_Chia_Se_Tai_LieuContext context)
        {
            _context = context;
        }

        // GET: ListNewsUser
        [Authentication]

        public async Task<IActionResult> Index()
        {
            var web_Chia_Se_Tai_LieuContext = _context.News.Include(n => n.CreateByNavigation);
            return View(await web_Chia_Se_Tai_LieuContext.ToListAsync());
        }

        // GET: ListNewsUser/Details/5
        [Authentication]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: ListNewsUser/Create
        [Authentication]

        public IActionResult Create()
        {
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "Address");
            return View();
        }

        // POST: ListNewsUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> Create([Bind("Id,Title,Description,Content,Image,CreateDate,CreateBy,Status")] News news)
        {
            if (ModelState.IsValid)
            {
                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "Address", news.CreateBy);
            return View(news);
        }

        // GET: ListNewsUser/Edit/5
        [Authentication]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FindAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "Address", news.CreateBy);
            return View(news);
        }

        // POST: ListNewsUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Content,Image,CreateDate,CreateBy,Status")] News news)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "Address", news.CreateBy);
            return View(news);
        }

        // GET: ListNewsUser/Delete/5
        [Authentication]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: ListNewsUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authentication]

        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.Id == id);
        }
    }
}

DAX_Block2_2024/Controllers/NewDetailController.cs
using DAX_Block2_2024.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace DAX_Block2_2024.Controllers
{
    public class NewDetailController : Controller
    {
        private Web_Chia_Se_Tai_LieuContext _context;
        private readonly ILogger<NewDetailController> _logger;
        public NewDetailController(ILogger<NewDetailController> logger, Web_Chia_Se_Tai_LieuContext context)
        {
            _context = context;
            _logger = logger;
        }


        public class ViewModelNewDetails
        {
            public IList<News> RelatedNewsTake4 { get; set; }
            public IList<CommentNews> CommentOfNews { get; set; }
            public News NewsDetails { get; set; }
        }
        // GET: NewDetailController/Details/5
        //Bỏ này vào bên HomeUser 
        //asp-controller="NewDetail" asp-action="Details" asp-route-id="@item.Id"
        [HttpGet]
        [Route("New/Detail/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // Fetch the main news item including its subjects
            var news = await _context.News
                .Include(n => n.CreateByNavigation)
                .Include(n => n.SubjectsNews)
                .ThenInclude(s => s.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (news == null)
            {
                return NotFound("News item not found.");
            }

            // Extract subject IDs associated with this news item
            var subjectIds = news.SubjectsNews.Select(sn => sn.SubjectId).ToList();

            // Fetch up to 4 related news items that share any of the same subject IDs
            var relatedNewsTake4 = await _context.News
                .Include(n => n.CreateByNavigation)
                .OrderBy(n => n.CreateDate)
                .Take(4)
                .ToListAsync();

            // Fetch comments associated with the news item
            var commentsOfNews = await _context.CommentNews
                .Include(c => c.Users)
                .Where(c => c.NewsId == id)
                .OrderBy(c => c.CommentDate)
                .ToListAsync();

            ViewModelNewDetails viewModel = new ViewModelNewDetails
            {
                RelatedNewsTake4 = relatedNewsTake4,
                CommentOfNews = commentsOfNews,
                NewsDetails = news
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetMoreRelatedNews(int newsId)
        {
            var news = await _context.News
                            .Include(n => n.CreateByNavigation)
                            .Include(n => n.SubjectsNews)
                            .ThenInclude(sn => sn.Subject)
                            .FirstOrDefaultAsync(m => m.Id == newsId);

            if (news == null)
            {
                return NotFound("News not found");
            }

            var subjectIds = news.SubjectsNews.Select(sn => sn.SubjectId).ToList();

            var additionalNews = await _context.News
                .Include(n => n.CreateByNavigation)
                .Include(n => n.SubjectsNews)
                .Where(n => n.Id != newsId && n.SubjectsNews.Any(sn => subjectIds.Contains(sn.SubjectId)))
                .ToListAsync();

            return PartialView("_RelatedNews", additionalNews);
        }


        public class CommentDTO
        {
            public string Comment { get; set; }
            public string Username { get; set; }
            public int NewsId { get; set; }
            public string CommentDate { get; set; }
        }

        [HttpPost]
        public async Task<IActionResult> PostComment([FromBody] CommentDTO commentData)
        {
            try
            {
                var user = await _context.Users.FirstOrDefaultAsync(u => u.UserName == commentData.Username);
                if (user == null)
                {
                    return Json(new { success = false, message = "User not found." });
                }

                if (!DateTime.TryParseExact(commentData.CommentDate, "MM/dd/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out DateTime parsedDate))
                {
                    return Json(new { success = false, message = "Invalid date format." });
                }

                var newComment = new CommentNews
                {
                    UsersId = user.Id,
                    NewsId = commentData.NewsId,
                    Content = commentData.Comment,
                    CommentDate = parsedDate
                };

                _context.CommentNews.Add(newComment);
                await _context.SaveChangesAsync();
                var formattedDate = ((DateTime)newComment.CommentDate).ToString("MM/dd/yyyy");
                return Json(new
                {
                    success = true,
                    fullName = user.FullName,
                    commentDate = formattedDate,
                    comment = newComment.Content
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "An error occurred while posting the comment.");
                _logger.LogError(ex, "An error occurred while posting the comment.");
                return Json(new { success = false, message = "An error occurred while posting the comment." });
            }
        }
            }
}

DAX_Block2_2024/Views/HomeUser/Index.cshtml
@model DAX_Block2_2024.Controllers.ViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row carousel slide" data-bs-ride="carousel">
    <img class="img-fluid" src="~/images/bg-header.png" alt="">
    <div class="container row position-absolute d-flex justify-content-center text-white">
        @foreach (var item in Model.News)
        {
            <div class="col-xl-6 col-sm-7 mt-60">
                <div class="row">
                    <div class="col-xl-2 col-sm-2">@item.CreateByNavigation.FullName</div>
                    <div class="col-xl-4 col-sm-4">@item.CreateDate.Date.ToShortDateString()</div>
                </div>
                <div class="pe-5 mt-111">
                    <a class="text-white nav-hover text-decoration-none"
                       asp-controller="DocumentDetails"
                       asp-action="Index"
                       asp-route-id="@item.Id">
                        <h2 class="fw-bold fs-62">Hot</h2>
                        <h2 class="fw-bold fs-62">@item.Title</h2>
                        <h2 class="fw-bold fs-62">@item.Content</h2>
                        <h2 class="fw-bold fs-62">@item.CreateDate.Date.ToShortDateString()</h2>
                    </a>
                </div>
            </div>
        }
        <div class="col-xl-6 col-sm-5 mt-60" style="width: 505px;">
            <div style="background-color: rgba(255, 255, 255, 0.2);">
                <div class="content p-4">
                    <h3 class="fw-bold mb-3" style="font-size: 31px;">Popular this week</h3>
                    @foreach (var item in Model.Document)
                    {
                        <a class="custom-link"
                           asp-controller="DocumentDetails"
                           asp-action="Index"
                           asp-route-id="@item.Id">
                            <div class="row hover-list-header mb-3">
                                <div class="col-xl-4 col-sm-4">
                                    <img class="img-fluid h-100" src="@item.Image" alt="Not Image">
                                </div>
                                <div class="col-xl-8 col-sm-8 mb-2">
                                    <div class="row pb-3 text-white">
                                        <div class="col-xl-4 col-sm-6 fs-12">@item.PostByNavigation.FullName</div>
                                        <div class="col-xl-8 col-sm-6 fs-12">@item.DatePost.Date.ToShortDateString()</div>
                                    </div>
                                    <p class="fs-16 fw-medium text-white">
                                        @item.Content
                                    </p>
                                </div>
                            </div>
                        </a>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="our-lateset-post mt-120 ">
        <div class="row">
            <div class="col-xl-10">
                <h4 class="fw-bold">Our Lateset Post</h4>
            </div>
            <div class="col-xl-2">
                <a class="btn text-white bg-F36326 hover-button-F36326 border-0 float-end"
                   asp-controller="ListNewsUser" asp-action="Index">View All</a>
            </div>
        </div>
        <div class="row mt-5">
            @foreach (var item in Model.Document8)
            {
                <div class="col-xl-3 mb-4">
                    <a class="custom-link"
                       asp-controller="DocumentDetails"
                       asp-action="Index"
                       asp-route-id="@item.Id">
                        <div class="card border-0 hover-list-popular">
                            <div class="position-relative">
                                <img src="@item.Image" class="img-fluid" alt="Not Image">
                                <div class="position-absolute bottom-0">
                                    <div class="btn rounded-0 border-0 bg-white color-9A9AB0">@item.PostByNavigation.FullName</div>
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="card-title fw-bold fs-24">
                                    @item.Content
                                </p>
                                <div class="row card-text fs-12 color-9A9AB0">
                                    <div class="col-xl-4">@item.PostByNavigation.FullName</div>
                                    <div class="col-xl-8">@item.DatePost.Date.ToShortDateString()</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }

        </div>
    </div>
    <div class="popular-document mt-120">
        <div class="row">
            <div class="col-xl-10">
                <h4 class="fw-bold">Popular News</h4>
            </div>
            <div class="col-xl-2">
                <a class="btn text-white border-0 hover-button-F36326 float-end bg-F36326"
                        asp-controller="Documents" asp-action="Index">
                    View All
                </a>
            </div>
        </div>
        <div class="row mt-5">
            @foreach (var item in Model.News)
            {
                <div class="col-xl-7">
                    <a class="custom-link"
                       asp-controller="NewDetail"
                       asp-action="Details"
                       asp-route-id="@item.Id">
                        <div class="card border-0 hover-list-popular">
                            <div class="position-relative">
                                <img src="@Url.Content("~/uploads/newsImage/" + item.Image)" class="img-fluid" alt="Not Image">
                                <div class="position-absolute bottom-0">
                                    <div class="btn rounded-0 border-0 bg-white color-9A9AB0">
                                        @item.CreateByNavigation.FullName
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="fs-24 card-title fw-medium">
                                    @item.Title
                                </p>
                                <div class="row card-text fs-12 color-9A9AB0">
                                    <div class="col-xl-4">@item.CreateByNavigation.FullName</div>
                                    <div class="col-xl-8">@item.CreateDate.Date.ToShortDateString()</div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            }
            <div class="col-xl-5">
                @foreach (var item in Model.News3)
                {
                    <div class="row hover-list-popular pt-2 pb-2">
                        <a class="custom-link"
                           asp-controller="NewDetail"
                           asp-action="Details"
                           asp-route-id="@item.Id">
                            <div class="row">
                                <div class="col-xl-4 col-sm-4">
                                    <img class="img-fluid h-100" src="@Url.Content("~/uploads/newsImage/" + item.Image)" alt="">
                                </div>
                                <div class="col-xl-8 col-sm-8 mt-2 mb-2">
                                    <p class="fs-24 custom-link fw-medium text-black lh-sm">
                                        @item.Title
                                    </p>
                                    <div class="row color-9A9AB0">
                                        <div class="col-xl-3 col-sm-6 fs-12">@item.CreateByNavigation.FullName</div>
                                        <div class="col-xl-9 col-sm-6 fs-12">@item.CreateDate.Date.ToShortDateString()</div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="recommended-for-you mt-120">
        <div class="row">
            <div class="col-xl-8">
                <h4 class="fw-bold">Recommended For You</h4>
            </div>
            <div class="col-xl-4">
                <nav aria-label="Page navigation example">
                    @if (Model.PagingInfo.TotalPages > 1)
                    {
                        <ul class="pagination float-end">
                            @for (int i = 1; i <= Model.PagingInfo.TotalPages; i++)
                            {
                                <li class="page-item @(i == Model.PagingInfo.CurrentPage ? "active" : "")">
                                    <a class="page-link" href="?page=@i">@i</a>
                                </li>
                            }
                        </ul>
                    }
                </nav>
            </div>

            <div class="row mt-5">
                @foreach (var item in Model.NewsFull)
                {
                    <div class="col-xl-6">
                        <a class="custom-link"
                           asp-controller="NewDetail"
                           asp-action="Details"
                           asp-route-id="@item.Id">
                            <div class="card border-0 hover-list-popular">
                                <div class="position-relative">
                                    <img src="@Url.Content("~/uploads/newsImage/" + item.Image)" class="img-fluid" alt="...">
                                    <div class="position-absolute bottom-0">
                                        <div class="btn rounded-0 border-0 bg-white color-9A9AB0">
                                            @item.CreateByNavigation.FullName
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title fs-24 fw-medium">
                                        @item.Title
                                    </h5>
                                    <div class="row card-text fs-12 color-9A9AB0">
                                        <div class="col-xl-4">@item.CreateByNavigation.FullName</div>
                                        <div class="col-xl-4">@item.CreateDate.Date.ToShortDateString()</div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

DAX_Block2_2024/Views/HomeUser/Login.cshtml
@{
    ViewData["Title"] = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model DAX_Block2_2024.Entities.User
@using (Html.BeginForm("Login", "HomeUser", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container pt-5">
        <div class="row g-4 mx-auto" style="max-width: 500px">
            <div class="col-12">
                <label for="validationCustomUsername" class="form-label">Username</label>
                <div class="input-group border-bottom">
                    <span class="input-group-text border-0 bg-transparent"
                          id="inputGroupPrepend"><i class="fa-solid fa-user"></i></span>
                    @Html.TextBoxFor(x => x.UserName, new { id = "validationCustomUsername", @class = "form-control form-control-lg border-0", aria_describedby = "inputGroupPrepend", required = "required", autocomplete = "off", placeholder = "Enter Username" })
                </div>
            </div>
            <div class="col-12">
                <div class="d-flex justify-content-between align-items-center">
                    <label for="validationCustomPassword" class="form-label"> Mật khẩu: </label>
                    <button class="btn visibility-toggle border-0" type="button">
                        <i class="fa-regular fa-eye" id="visibility-icon"></i>
                    </button>
                </div>
                <div class="input-group border-bottom">
                    <span class="input-group-text border-0 bg-transparent"
                          id="inputGroupPrepend"><i class="fa-solid fa-lock"></i></span>
                    @Html.TextBoxFor(x => x.PassWord, new { id = "validationCustomPassword", @class = "form-control form-control-lg border-0", name = "Password", placeholder = "Enter Password", aria_describedby = "inputGroupPrepend", required = "required", autocomplete = "off", type = "password" })
                </div>
            </div>
            <div class="col-12">
                <button class="btn px-4 btn-outline-light float-start mt-4" type="submit"
                        style="background-color: #ff9800; color: white;">
                    Đăng nhập
                </button>
            </div>
        </div>
    </div>
}