DAX_Block2_2024/Entities/News.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace DAX_Block2_2024.Entities
{
    public partial class News
    {
        public News()
        {
            CommentNews = new HashSet<CommentNews>();
            SubjectsNews = new HashSet<SubjectsNews>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public bool? Status { get; set; }

        public virtual User CreateByNavigation { get; set; }
        public virtual ICollection<CommentNews> CommentNews { get; set; }
        public virtual ICollection<SubjectsNews> SubjectsNews { get; set; }
    }
}

DAX_Block2_2024/Areas/Admin/Controllers/NewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DAX_Block2_2024.Entities;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Net;
using DAX_Block2_2024.Models;

namespace DAX_Block2_2024.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class NewController : Controller
    {
        private readonly Web_Chia_Se_Tai_LieuContext _context;

        public NewController(Web_Chia_Se_Tai_LieuContext context)
        {
            _context = context;
        }

        // GET: Admin/New
        [Authentication]

        public async Task<IActionResult> Index()
        {
            var web_Chia_Se_Tai_LieuContext = _context.News.Include(n => n.CreateByNavigation);
            return View(await web_Chia_Se_Tai_LieuContext.ToListAsync());
        }

        // GET: Admin/New/Details/5
        [Authentication]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: Admin/New/Create
        [Authentication]

        public IActionResult Create()
        {
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name"); // Ensure this line is added
            return View();
        }

        // POST: Admin/New/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> Create([Bind("Id,Title,Description,Content,Image,Status,CreateDate,CreateBy")] News news, IFormFile ImageFile, int? subjectId)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.Length > 0)
                {
                    var fileName = WebUtility.HtmlEncode(Path.GetFileName(ImageFile.FileName));
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads/newsImage", fileName);

                    if (!System.IO.File.Exists(filePath))
                    {
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await ImageFile.CopyToAsync(fileStream);
                        }
                    }
                    news.Image = fileName;
                }
                _context.Add(news);
                await _context.SaveChangesAsync();
                if (subjectId.HasValue)
                {
                    var subjectNews = new SubjectsNews
                    {
                        NewsId = news.Id,
                        SubjectId = subjectId.Value
                    };
                    _context.SubjectsNews.Add(subjectNews);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "UserName", news.CreateBy);
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(news);
        }

        // GET: Admin/New/Edit/5
        [Authentication]

        public IActionResult Edit()
        {
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "UserName");
            ViewData["NewsList"] = new SelectList(_context.News, "Id", "Content");
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View();
        }
        [HttpGet]
        [Authentication]

        public IActionResult GetNewsDetails(int id)
        {
            var news = _context.News
                .Include(n => n.SubjectsNews) 
                .SingleOrDefault(n => n.Id == id);

            if (news == null)
            {
                return NotFound();
            }

            string formattedDate = news.CreateDate.ToString("dd/MM/yyyy");
            var firstSubjectId = news.SubjectsNews.FirstOrDefault()?.SubjectId ?? -1;

            return Ok(new
            {
                title = news.Title,
                content = news.Content,
                description = news.Description,
                createDate = formattedDate,
                image = news.Image,
                createdBy = news.CreateBy,
                status = news.Status,
                subjectId = firstSubjectId 
            });
        }



        // POST: Admin/New/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Content,Image,Status,CreateDate,CreateBy")] News news, IFormFile ImageFile, int? subjectId)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (ImageFile != null && ImageFile.Length > 0)
                    {
                        var fileName = WebUtility.HtmlEncode(Path.GetFileName(ImageFile.FileName));
                        var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads/newsImage", fileName);

                        if (!System.IO.File.Exists(filePath))
                        {
                            using (var fileStream = new FileStream(filePath, FileMode.Create))
                            {
                                await ImageFile.CopyToAsync(fileStream);
                            }
                        }
                        news.Image = fileName;
                    }
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                    if (subjectId.HasValue)
                    {
                        var subjectNews = new SubjectsNews
                        {
                            NewsId = news.Id,
                            SubjectId = subjectId.Value
                        };
                        _context.SubjectsNews.Update(subjectNews);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["NewsList"] = new SelectList(_context.News, "Id", "Content", news.Id);
            ViewData["CreateBy"] = new SelectList(_context.Users, "Id", "UserName", news.CreateBy);
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Name");
            return View(news);
        }


        //GET: Admin/New/Delete/5
        [Authentication]

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .Include(n => n.CreateByNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: Admin/New/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authentication]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.FindAsync(id);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authentication]


        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.Id == id);
        }
    }


}

DAX_Block2_2024/Areas/Admin/Views/New/Create.cshtml
@model DAX_Block2_2024.Entities.News

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add News</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item">News</li>
                    <li class="breadcrumb-item active">Add News</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Please fill full fields</h3>
                    </div>
                    <form asp-area="Admin" asp-controller="New" asp-action="Create" id="quickForm" method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Title" class="control-label">Name</label>
                                    <input asp-for="Title" class="form-control" id="exampleInputName1" placeholder="Name" required>
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Content" class="control-label">Content</label>
                                    <input asp-for="Content" class="form-control" id="exampleInputContent1" placeholder="Content" required>
                                    <span asp-validation-for="Content" class="text-danger"></span>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="CreateDate" class="control-label">Date</label>
                                    <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                        <input asp-for="CreateDate" type="text" class="form-control datetimepicker-input" data-target="#reservationdate" required>
                                        <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="CreateDate" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label asp-for="CreateBy" class="control-label">Post By</label>
                                    <select asp-for="CreateBy" asp-items="@((SelectList)ViewData["CreateBy"])" class="form-control select2 select2-accessible" style="width: 100%;" required>
                                    </select>
                                    <span asp-validation-for="CreateBy" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Image" class="control-label">Files</label>
                                    <input type="file" class="form-control" name="ImageFile" id="exampleInputFile1" required>
                                    <span asp-validation-for="Image" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Status" class="control-label">Status</label>
                                    <select asp-for="Status" class="form-control" required>
                                        <option value="" selected disabled>News Status</option>
                                        <option value="true">Active</option>
                                        <option value="false">Inactive</option>
                                    </select>
                                    <span asp-validation-for="Status" class="text-danger"></span>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Description" class="control-label">Description</label>
                                    <textarea asp-for="Description" cols="100%" rows="7" class="form-control" id="Decription" placeholder="Description" required></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label for="SubjectId" class="control-label">Subject</label>
                                    <select id="SubjectId" name="SubjectId" class="form-control">
                                        <option value="-1">Select a Subject</option>
                                        @foreach (SelectListItem subject in (SelectList)ViewData["SubjectId"])
                                        {
                                            <option value="@subject.Value">@subject.Text</option>
                                        }
                                    </select>
                                </div>
                            </div>


                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
            <!-- right column -->
            <div class="col-md-6">

            </div>
            <!--/.col (right) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DAX_Block2_2024/Areas/Admin/Views/New/Delete.cshtml
@model DAX_Block2_2024.Entities.News

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateByNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateByNavigation.Address)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DAX_Block2_2024/Areas/Admin/Views/New/Details.cshtml
@model DAX_Block2_2024.Entities.News

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Details</h1>

<div>
    <h4>News</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateByNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateByNavigation.Address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DAX_Block2_2024/Areas/Admin/Views/New/Edit.cshtml
@model DAX_Block2_2024.Entities.News

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Add News</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item">News</li>
                    <li class="breadcrumb-item active">Add News</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Please fill full fields</h3>
                    </div>
                    <form asp-area="Admin" asp-controller="New" asp-action="Edit" id="quickForm newsSelect" method="post" enctype="multipart/form-data">
                        <div class="card-body">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="row">
                                <div class="col-lg-12 form-group">
                                    <label asp-for="Id" class="control-label">News To Update</label>
                                    <select asp-for="Id" asp-items="@((SelectList)ViewData["NewsList"])" class="form-control select2" style="width: 100%;" required onchange="fetchNewsData(this.value)">
                                        <option value="-1">Select a news to update</option>
                                    </select>
                                    <span asp-validation-for="Id" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Title" class="control-label">Name</label>
                                    <input asp-for="Title" class="form-control" id="exampleInputName1" placeholder="Name" required>
                                    <span asp-validation-for="Title" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Content" class="control-label">Content</label>
                                    <input asp-for="Content" class="form-control" id="exampleInputContent1" placeholder="Content" required>
                                    <span asp-validation-for="Content" class="text-danger"></span>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="CreateDate" class="control-label">Date</label>
                                    <div class="input-group date" id="reservationdate" data-target-input="nearest">
                                        <input asp-for="CreateDate" type="text" class="form-control datetimepicker-input" id="CreateDate" data-target="#reservationdate" required>
                                        <div class="input-group-append" data-target="#reservationdate" data-toggle="datetimepicker">
                                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="CreateDate" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label asp-for="CreateBy" class="control-label">Post By</label>
                                    <select asp-for="CreateBy" asp-items="@((SelectList)ViewData["CreateBy"])" class="form-control select2 select2-accessible" style="width: 100%;" required>
                                        <!-- Options will be populated here -->
                                    </select>
                                    <span asp-validation-for="CreateBy" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Image" class="control-label">Files</label>
                                    <input type="file" class="form-control" name="ImageFile" id="exampleInputFile1" required>
                                    <span asp-validation-for="Image" class="text-danger"></span>
                                </div>
                                <div class="col-lg-6 form-group">
                                    <label asp-for="Status" class="control-label">Status</label>
                                    <select asp-for="Status" class="form-control" required>
                                        <option value="" selected disabled>Select News Status</option>
                                        <option value="true">Active</option>
                                        <option value="false">Inactive</option>
                                    </select>
                                    <span asp-validation-for="Status" class="text-danger"></span>
                                </div>

                            </div>
                            <div class="row">
                                <div class="col-lg-12 form-group">
                                    <label asp-for="Description" class="control-label">Description</label>
                                    <textarea asp-for="Description" cols="100%" rows="7" class="form-control" id="Decription" placeholder="Description" required></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                            </div>


                        </div>

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
            <!-- right column -->
            <div class="col-md-6">

            </div>
            <!--/.col (right) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

<script>
    $(document).ready(function () {
        $('#CreateDate').datetimepicker({
            format: 'DD/MM/YYYY'
        });
    });
    function fetchNewsData(newsId) {
        if (newsId) {
            fetch(`/Admin/New/GetNewsDetails?id=${newsId}`)
                .then(response => response.json())
                .then(data => {
                    if (data) {
                        document.getElementById('exampleInputName1').value = data.title;
                        document.getElementById('exampleInputContent1').value = data.content;
                        document.getElementById('Decription').value = data.description;
                        $('#CreateDate').datetimepicker('date', data.createDate);
                        let createBySelect = document.querySelector('select[name="CreateBy"]');
                        Array.from(createBySelect.options).forEach(option => {
                            if (option.value === data.createdBy.toString()) {
                                createBySelect.value = data.createdBy.toString();
                            }
                        });

                        let statusSelect = document.querySelector('select[name="Status"]');
                        statusSelect.value = data.status.toString();
                    }
                }).catch(error => console.error('Error fetching news data:', error));
        } else {
            console.log('No news selected');
        }
    }

</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}